services:
  - type: web
    name: expense-tracker
    env: go
    go_version: 1.25.4
    build_command: go build -o main ./cmd/api
    start_command: ./main
    env_vars:
      - key: PORT
        value: "8080"
      - key: JWT_SECRET
